// <auto-generated>
// This file was generated by takumi-native build.rs
// Do not edit manually.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace TakumiSharp.Models;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ContainerNode), "container")]
[JsonDerivedType(typeof(ImageNode), "image")]
[JsonDerivedType(typeof(TextNode), "text")]
public abstract class NodeKind { }

public class ContainerNode : NodeKind
{
    [JsonPropertyName("preset")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Style? Preset { get; set; }

    [JsonPropertyName("style")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Style? Style { get; set; }

    [JsonPropertyName("children")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<NodeKind>? Children { get; set; }

    [JsonPropertyName("tw")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TailwindValues? Tw { get; set; }

}

public class ImageNode : NodeKind
{
    [JsonPropertyName("preset")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Style? Preset { get; set; }

    [JsonPropertyName("style")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Style? Style { get; set; }

    [JsonPropertyName("src")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string Src { get; set; } = string.Empty;

    [JsonPropertyName("width")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public float? Width { get; set; }

    [JsonPropertyName("height")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public float? Height { get; set; }

    [JsonPropertyName("tw")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TailwindValues? Tw { get; set; }

}

public class TextNode : NodeKind
{
    [JsonPropertyName("preset")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Style? Preset { get; set; }

    [JsonPropertyName("style")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Style? Style { get; set; }

    [JsonPropertyName("text")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string Text { get; set; } = string.Empty;

    [JsonPropertyName("tw")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TailwindValues? Tw { get; set; }

}

/// <summary>
/// CSS-like style properties for layout and rendering.
/// </summary>
public class Style
{
    [JsonPropertyName("boxSizing")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BoxSizing { get; set; }

    [JsonPropertyName("opacity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Opacity { get; set; }

    [JsonPropertyName("display")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Display { get; set; }

    [JsonPropertyName("width")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Width { get; set; }

    [JsonPropertyName("height")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Height { get; set; }

    [JsonPropertyName("maxWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MaxWidth { get; set; }

    [JsonPropertyName("maxHeight")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MaxHeight { get; set; }

    [JsonPropertyName("minWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MinWidth { get; set; }

    [JsonPropertyName("minHeight")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MinHeight { get; set; }

    [JsonPropertyName("aspectRatio")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? AspectRatio { get; set; }

    [JsonPropertyName("padding")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Padding { get; set; }

    [JsonPropertyName("paddingInline")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PaddingInline { get; set; }

    [JsonPropertyName("paddingBlock")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PaddingBlock { get; set; }

    [JsonPropertyName("paddingTop")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PaddingTop { get; set; }

    [JsonPropertyName("paddingRight")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PaddingRight { get; set; }

    [JsonPropertyName("paddingBottom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PaddingBottom { get; set; }

    [JsonPropertyName("paddingLeft")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PaddingLeft { get; set; }

    [JsonPropertyName("margin")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Margin { get; set; }

    [JsonPropertyName("marginInline")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MarginInline { get; set; }

    [JsonPropertyName("marginBlock")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MarginBlock { get; set; }

    [JsonPropertyName("marginTop")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MarginTop { get; set; }

    [JsonPropertyName("marginRight")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MarginRight { get; set; }

    [JsonPropertyName("marginBottom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MarginBottom { get; set; }

    [JsonPropertyName("marginLeft")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MarginLeft { get; set; }

    [JsonPropertyName("inset")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Inset { get; set; }

    [JsonPropertyName("insetInline")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? InsetInline { get; set; }

    [JsonPropertyName("insetBlock")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? InsetBlock { get; set; }

    [JsonPropertyName("top")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Top { get; set; }

    [JsonPropertyName("right")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Right { get; set; }

    [JsonPropertyName("bottom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Bottom { get; set; }

    [JsonPropertyName("left")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Left { get; set; }

    [JsonPropertyName("flexDirection")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FlexDirection { get; set; }

    [JsonPropertyName("justifySelf")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? JustifySelf { get; set; }

    [JsonPropertyName("justifyContent")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? JustifyContent { get; set; }

    [JsonPropertyName("alignContent")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? AlignContent { get; set; }

    [JsonPropertyName("justifyItems")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? JustifyItems { get; set; }

    [JsonPropertyName("alignItems")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? AlignItems { get; set; }

    [JsonPropertyName("alignSelf")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? AlignSelf { get; set; }

    [JsonPropertyName("flexWrap")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FlexWrap { get; set; }

    [JsonPropertyName("flexBasis")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FlexBasis { get; set; }

    [JsonPropertyName("position")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Position { get; set; }

    [JsonPropertyName("rotate")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Rotate { get; set; }

    [JsonPropertyName("scale")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Scale { get; set; }

    [JsonPropertyName("scaleX")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? ScaleX { get; set; }

    [JsonPropertyName("scaleY")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? ScaleY { get; set; }

    [JsonPropertyName("transform")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Transform { get; set; }

    [JsonPropertyName("transformOrigin")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TransformOrigin { get; set; }

    [JsonPropertyName("translate")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Translate { get; set; }

    [JsonPropertyName("translateX")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TranslateX { get; set; }

    [JsonPropertyName("translateY")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TranslateY { get; set; }

    [JsonPropertyName("mask")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Mask { get; set; }

    [JsonPropertyName("maskImage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MaskImage { get; set; }

    [JsonPropertyName("maskSize")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MaskSize { get; set; }

    [JsonPropertyName("maskPosition")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MaskPosition { get; set; }

    [JsonPropertyName("maskRepeat")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? MaskRepeat { get; set; }

    [JsonPropertyName("gap")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Gap { get; set; }

    [JsonPropertyName("columnGap")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? ColumnGap { get; set; }

    [JsonPropertyName("rowGap")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? RowGap { get; set; }

    [JsonPropertyName("flex")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Flex { get; set; }

    [JsonPropertyName("flexGrow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FlexGrow { get; set; }

    [JsonPropertyName("flexShrink")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FlexShrink { get; set; }

    [JsonPropertyName("borderRadius")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderRadius { get; set; }

    [JsonPropertyName("borderTopLeftRadius")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderTopLeftRadius { get; set; }

    [JsonPropertyName("borderTopRightRadius")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderTopRightRadius { get; set; }

    [JsonPropertyName("borderBottomRightRadius")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderBottomRightRadius { get; set; }

    [JsonPropertyName("borderBottomLeftRadius")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderBottomLeftRadius { get; set; }

    [JsonPropertyName("borderWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderWidth { get; set; }

    [JsonPropertyName("borderInlineWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderInlineWidth { get; set; }

    [JsonPropertyName("borderBlockWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderBlockWidth { get; set; }

    [JsonPropertyName("borderTopWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderTopWidth { get; set; }

    [JsonPropertyName("borderRightWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderRightWidth { get; set; }

    [JsonPropertyName("borderBottomWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderBottomWidth { get; set; }

    [JsonPropertyName("borderLeftWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderLeftWidth { get; set; }

    [JsonPropertyName("border")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Border { get; set; }

    [JsonPropertyName("objectFit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? ObjectFit { get; set; }

    [JsonPropertyName("overflow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Overflow { get; set; }

    [JsonPropertyName("overflowX")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? OverflowX { get; set; }

    [JsonPropertyName("overflowY")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? OverflowY { get; set; }

    [JsonPropertyName("objectPosition")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? ObjectPosition { get; set; }

    [JsonPropertyName("background")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Background { get; set; }

    [JsonPropertyName("backgroundImage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BackgroundImage { get; set; }

    [JsonPropertyName("backgroundPosition")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BackgroundPosition { get; set; }

    [JsonPropertyName("backgroundSize")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BackgroundSize { get; set; }

    [JsonPropertyName("backgroundRepeat")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BackgroundRepeat { get; set; }

    [JsonPropertyName("backgroundColor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BackgroundColor { get; set; }

    [JsonPropertyName("backgroundClip")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BackgroundClip { get; set; }

    [JsonPropertyName("boxShadow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BoxShadow { get; set; }

    [JsonPropertyName("gridAutoColumns")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? GridAutoColumns { get; set; }

    [JsonPropertyName("gridAutoRows")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? GridAutoRows { get; set; }

    [JsonPropertyName("gridAutoFlow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? GridAutoFlow { get; set; }

    [JsonPropertyName("gridColumn")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? GridColumn { get; set; }

    [JsonPropertyName("gridRow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? GridRow { get; set; }

    [JsonPropertyName("gridTemplateColumns")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? GridTemplateColumns { get; set; }

    [JsonPropertyName("gridTemplateRows")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? GridTemplateRows { get; set; }

    [JsonPropertyName("gridTemplateAreas")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? GridTemplateAreas { get; set; }

    [JsonPropertyName("textOverflow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextOverflow { get; set; }

    [JsonPropertyName("textTransform")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextTransform { get; set; }

    [JsonPropertyName("fontStyle")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FontStyle { get; set; }

    [JsonPropertyName("borderColor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BorderColor { get; set; }

    [JsonPropertyName("color")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Color { get; set; }

    [JsonPropertyName("filter")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Filter { get; set; }

    [JsonPropertyName("backdropFilter")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? BackdropFilter { get; set; }

    [JsonPropertyName("fontSize")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FontSize { get; set; }

    [JsonPropertyName("fontFamily")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FontFamily { get; set; }

    [JsonPropertyName("lineHeight")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? LineHeight { get; set; }

    [JsonPropertyName("fontWeight")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FontWeight { get; set; }

    [JsonPropertyName("fontVariationSettings")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FontVariationSettings { get; set; }

    [JsonPropertyName("fontFeatureSettings")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? FontFeatureSettings { get; set; }

    [JsonPropertyName("lineClamp")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? LineClamp { get; set; }

    [JsonPropertyName("textAlign")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextAlign { get; set; }

    [JsonPropertyName("webkitTextStroke")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WebkitTextStroke { get; set; }

    [JsonPropertyName("webkitTextStrokeWidth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WebkitTextStrokeWidth { get; set; }

    [JsonPropertyName("webkitTextStrokeColor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WebkitTextStrokeColor { get; set; }

    [JsonPropertyName("textShadow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextShadow { get; set; }

    [JsonPropertyName("textDecoration")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextDecoration { get; set; }

    [JsonPropertyName("textDecorationLine")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextDecorationLine { get; set; }

    [JsonPropertyName("textDecorationColor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextDecorationColor { get; set; }

    [JsonPropertyName("letterSpacing")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? LetterSpacing { get; set; }

    [JsonPropertyName("wordSpacing")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WordSpacing { get; set; }

    [JsonPropertyName("imageRendering")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? ImageRendering { get; set; }

    [JsonPropertyName("overflowWrap")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? OverflowWrap { get; set; }

    [JsonPropertyName("wordBreak")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WordBreak { get; set; }

    [JsonPropertyName("clipPath")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? ClipPath { get; set; }

    [JsonPropertyName("clipRule")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? ClipRule { get; set; }

    [JsonPropertyName("whiteSpace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WhiteSpace { get; set; }

    [JsonPropertyName("whiteSpaceCollapse")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WhiteSpaceCollapse { get; set; }

    [JsonPropertyName("textWrapMode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextWrapMode { get; set; }

    [JsonPropertyName("textWrapStyle")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextWrapStyle { get; set; }

    [JsonPropertyName("textWrap")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? TextWrap { get; set; }

}

/// <summary>
/// Tailwind CSS classes string. Parsed and applied at runtime.
/// </summary>
[JsonConverter(typeof(TailwindValuesConverter))]
public class TailwindValues
{
    public string Value { get; set; } = string.Empty;

    public TailwindValues() { }
    public TailwindValues(string value) => Value = value;

    public static implicit operator TailwindValues(string value) => new(value);
    public static implicit operator string(TailwindValues tw) => tw.Value;
}

public class TailwindValuesConverter : JsonConverter<TailwindValues>
{
    public override TailwindValues? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => reader.GetString() is string s ? new TailwindValues(s) : null;

    public override void Write(Utf8JsonWriter writer, TailwindValues value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.Value);
}
