// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace TakumiSharp.Bindings
{
    internal static unsafe partial class NativeBindings
    {
        const string __DllName = "libtakumi";





        /// <summary>
        ///  Loads and stores font data into the global font context.
        ///
        ///  # Safety
        ///
        ///  - `data` must be a valid pointer to a byte array of at least `len` bytes.
        ///  - The data must remain valid for the duration of this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "global_font_context_load_and_store", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool global_font_context_load_and_store(byte* data, nuint len);

        /// <summary>
        ///  Calculates the required buffer size for rendering a node to an image.
        ///
        ///  # Safety
        ///
        ///  - `node_str` must be a valid null-terminated C string pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "render_calculate_buffer_size_with_format", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong render_calculate_buffer_size_with_format(byte* node_str, Viewport viewport, ImageFormat format);

        /// <summary>
        ///  Renders a node to an image and writes it to a buffer.
        ///
        ///  # Safety
        ///
        ///  - `node_str` must be a valid null-terminated C string pointer.
        ///  - `out_buffer` must be a valid pointer to a buffer of at least `buffer_len` bytes.
        ///  - The buffer must remain valid for the duration of this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "render_to_buffer_with_format", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool render_to_buffer_with_format(byte* node_str, Viewport viewport, ImageFormat format, byte* out_buffer, ulong buffer_len);


    }

    /// <summary>
    ///  The viewport for the image renderer.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Viewport
    {
        /// <summary>
        ///  The width of the viewport in pixels, or -1 for none/auto.
        /// </summary>
        public int width;
        /// <summary>
        ///  The height of the viewport in pixels, or -1 for none/auto.
        /// </summary>
        public int height;
        /// <summary>
        ///  The font size in pixels, used for em and rem units.
        /// </summary>
        public float font_size;
        /// <summary>
        ///  The device pixel ratio
        /// </summary>
        public float device_pixel_ratio;
    }


    internal enum ImageFormat : byte
    {
        /// <summary>
        ///  An Image in PNG Format
        /// </summary>
        Png,
        /// <summary>
        ///  An Image in JPEG Format
        /// </summary>
        Jpeg,
        /// <summary>
        ///  An Image in GIF Format
        /// </summary>
        Gif,
        /// <summary>
        ///  An Image in WEBP Format
        /// </summary>
        WebP,
        /// <summary>
        ///  An Image in general PNM Format
        /// </summary>
        Pnm,
        /// <summary>
        ///  An Image in TIFF Format
        /// </summary>
        Tiff,
        /// <summary>
        ///  An Image in TGA Format
        /// </summary>
        Tga,
        /// <summary>
        ///  An Image in DDS Format
        /// </summary>
        Dds,
        /// <summary>
        ///  An Image in BMP Format
        /// </summary>
        Bmp,
        /// <summary>
        ///  An Image in ICO Format
        /// </summary>
        Ico,
        /// <summary>
        ///  An Image in Radiance HDR Format
        /// </summary>
        Hdr,
        /// <summary>
        ///  An Image in OpenEXR Format
        /// </summary>
        OpenExr,
        /// <summary>
        ///  An Image in farbfeld Format
        /// </summary>
        Farbfeld,
        /// <summary>
        ///  An Image in AVIF Format
        /// </summary>
        Avif,
        /// <summary>
        ///  An Image in QOI Format
        /// </summary>
        Qoi,
    }


}
